#!/bin/bash

# Defaults suggested
apt-get install jpegoptim pngquant gifsicle advancecomp python-pip python-virtualenv python-dev libxml2-dev libxslt1-dev libbz2-dev p7zip-full python-pillow gif2apng imagemagick

# Extra stuff
apt-get install zlib1g-dev
